apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: microservices-demo
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: database # PROBLEMA: Label que NO coincide con el pod
