# Base de datos con label CORRECTO
apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  namespace: microservices-demo
  labels:
    app: database
spec:
  containers:
    - name: postgres
      image: postgres:15-alpine
      env:
        - name: POSTGRES_DB
          value: authdb
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: password123
      ports:
        - containerPort: 5432
      resources:
        requests:
          memory: "256Mi"
        limits:
          memory: "512Mi"
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - pg_isready -U admin -d authdb
        initialDelaySeconds: 10
        periodSeconds: 10
